apiVersion: v1
kind: Secret
metadata:
  name: apns-cert-secret
  namespace: {{ include "drinkwater.namespace" . }}
  labels:
    {{- include "drinkwater.labels" . | nindent 4 }}
type: Opaque
stringData:
  cert-password: {{ .Values.pushService.secret.certPassword | quote }}
